# Generated by Django 4.1.5 on 2023-01-28 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "credit_from",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                ("credit_from_amount", models.IntegerField(default=None, null=True)),
                (
                    "credit_for",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                ("credit_for_amount", models.IntegerField(default=None, null=True)),
                ("color_1", models.CharField(max_length=10)),
                ("color_2", models.CharField(default=None, max_length=10, null=True)),
                ("price", models.IntegerField()),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Civ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pcolor", models.CharField(max_length=10)),
                ("scolor", models.CharField(max_length=10)),
                ("start_territory", models.CharField(max_length=50)),
                ("ast_rank", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board_name",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "board_file",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "territories_file",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "adv_card_deck",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                ("max_stock", models.IntegerField(default=55)),
                ("max_cities", models.IntegerField(default=9)),
                ("max_players", models.IntegerField(default=18)),
                ("timespan", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("turn", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("g_id", models.CharField(max_length=300)),
                ("treasury", models.IntegerField(default=0)),
                ("tax_rate", models.IntegerField(default=2)),
                ("pays_tax", models.BooleanField(default=False)),
                ("back_tax", models.IntegerField(default=0)),
                ("census", models.IntegerField(default=0)),
                ("ast_position", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TradeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("level", models.IntegerField()),
                ("max_set", models.IntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_deck",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_cards",
                        to="game.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geometry", models.JSONField()),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=10)),
                ("support", models.IntegerField()),
                ("has_city_cite", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territories",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.IntegerField()),
                ("has_city", models.BooleanField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territories",
                        to="game.player",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.territory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerAdvCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_cost", models.IntegerField()),
                (
                    "card_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.advcard",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adv_cards",
                        to="game.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="adv_credits",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="void",
                to="game.playercredit",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="civ",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="void",
                to="game.civ",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="game.game",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="active_player",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_in_game",
                to="game.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="game.gamesettings",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="phase",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="game.phase",
            ),
        ),
        migrations.CreateModel(
            name="Boat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upkeep_paid", models.BooleanField(default=False)),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boats",
                        to="game.playerterritory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("geometry", models.JSONField()),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvCardAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=30)),
                ("credit", models.IntegerField()),
                (
                    "adv_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities",
                        to="game.advcard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advcard",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adv_cards",
                to="game.game",
            ),
        ),
    ]
