# Generated by Django 4.1.5 on 2023-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_game_settings_gamesettings_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="board_file",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gamesettings",
            name="board_name",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gamesettings",
            name="territories_file",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gamesettings",
            name="time",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
