# Generated by Django 4.1.5 on 2023-01-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_game_game_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="settings",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="game.gamesettings",
            ),
        ),
        migrations.CreateModel(
            name="AdjacentTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="void",
                        to="game.territory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacencies",
                        to="game.territory",
                    ),
                ),
            ],
        ),
    ]
