# Generated by Django 4.1.5 on 2023-01-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_game_settings_adjacentterritory"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="board",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Board",),
    ]
