# Generated by Django 4.1.5 on 2023-01-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_board_delete_board"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="g_id",),
        migrations.AlterField(
            model_name="territory",
            name="support",
            field=models.IntegerField(default=0),
        ),
    ]
