# Generated by Django 4.1.5 on 2023-01-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remove_player_g_id_alter_territory_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game", name="board", field=models.JSONField(null=True),
        ),
    ]
