# Generated by Django 4.1.5 on 2023-02-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_game_board"),
    ]

    operations = [
        migrations.RemoveField(model_name="gamesettings", name="board_file",),
        migrations.RemoveField(model_name="gamesettings", name="board_name",),
        migrations.RemoveField(model_name="gamesettings", name="territories_file",),
        migrations.AddField(
            model_name="boat",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boats",
                to="game.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="civ",
            name="game_settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="civs",
                to="game.gamesettings",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_name", models.CharField(max_length=50)),
                ("board_file", models.CharField(max_length=50)),
                ("territories_file", models.CharField(max_length=50)),
                (
                    "game_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="game.gamesettings",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesettings",
            name="board",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="void",
                to="game.board",
            ),
        ),
    ]
