# Generated by Django 4.1.5 on 2023-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_remove_gamesettings_board_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="gamesettings", name="max_players",),
        migrations.AddField(
            model_name="board",
            name="max_players",
            field=models.IntegerField(default=18),
        ),
    ]
