# Generated by Django 4.1.5 on 2023-02-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_remove_gamesettings_max_players_board_max_players"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="board",),
        migrations.AddField(
            model_name="board",
            name="board_geometry",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
