# Generated by Django 4.1.5 on 2023-02-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_remove_game_board_board_board_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="host",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_for",
                to="game.player",
            ),
            preserve_default=False,
        ),
    ]
