# Generated by Django 4.1.5 on 2023-02-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_alter_phase_duration_alter_phase_turn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="civ",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player",
                to="game.civ",
            ),
        ),
    ]
