# Generated by Django 4.1.5 on 2023-02-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_alter_player_civ"),
    ]

    operations = [
        migrations.RemoveField(model_name="board", name="board_file",),
    ]
