# Generated by Django 4.1.5 on 2023-02-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_remove_board_board_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="settings",),
        migrations.AddField(
            model_name="gamesettings",
            name="game",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="game.game",
            ),
        ),
    ]
